### ISSUE TITLE
Please add Khmer language

### ISSUE THREAD

**Issue by ghost** [AlexxIT/FasterWhisper#6]
Dear developer, I have tested FasterWhisper about 3 days. It's working well with English language. But unfortunately it's not supported Khmer language. Can you add Khmer language please? Thanks you.

**Comment by AlexxIT** [comment]
Check readme. I'm not developing languages or Speech-to-Text engine.
https://github.com/AlexxIT/FasterWhisper?tab=readme-ov-file#faster-whisper-for-home-assistant
